# Generated by Django 5.1.15 on 2026-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('role_applied', models.CharField(max_length=150)),
                ('portfolio_link', models.URLField(blank=True, max_length=500)),
                ('cover_letter', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('service_interested', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=250)),
                ('short_description', models.TextField(help_text='Short summary shown on cards')),
                ('sector', models.CharField(choices=[('local-business', 'Local Business'), ('education', 'Education & Communities'), ('portfolios', 'Personal Portfolios')], default='local-business', help_text='Industry sector category', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Uploaded project screenshot', null=True, upload_to='portfolio/')),
                ('tech_tags', models.JSONField(blank=True, default=list, help_text="JSON list of tech stack tags e.g. ['Next.js', 'Django']")),
                ('live_link', models.URLField(blank=True, help_text='External URL to live site', max_length=500)),
                ('is_featured', models.BooleanField(default=True, help_text='Feature this project in portfolio lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
