# Generated by Django 5.1.15 on 2026-07-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolioproject_results_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name e.g. Local Business', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug e.g. local-business', max_length=110, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description shown in tooltips/dropdowns', max_length=300)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g. Store, GraduationCap, User)', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title shown on Navbar and Services page', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug e.g. business-websites', max_length=220, unique=True)),
                ('short_description', models.TextField(help_text='One-to-two sentence description')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name (e.g. Globe, ShoppingCart, Video, Target, MapPin, ShieldCheck)', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in dropdowns and lists')),
                ('is_active', models.BooleanField(default=True, help_text='Active status toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
