# Generated by Django 5.1.15 on 2026-07-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Linked Category model for dynamic portfolio mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="JSON list of features e.g. ['Custom Design', 'SEO Optimized']"),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed long description for the service detail page'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_text',
            field=models.CharField(blank=True, help_text='Pricing highlight e.g. Starting at ₹15,000/mo', max_length=150),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='sector',
            field=models.CharField(choices=[('local-business', 'Local Business'), ('education', 'Education & Communities'), ('portfolios', 'Personal Portfolios')], default='local-business', help_text='Industry sector category fallback', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(help_text='One-to-two sentence summary description'),
        ),
    ]
