# Generated by Django 5.1.15 on 2026-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolioproject_category_service_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Design/UI Issue', 'Design/UI Issue'), ('Other', 'Other')], default='Bug Report', max_length=50)),
                ('message', models.TextField(help_text='Detailed feedback or bug description')),
                ('contact_info', models.CharField(blank=True, help_text='Optional email or phone for follow-up', max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Feedback',
                'verbose_name_plural': 'Website Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
