# Generated by Django 5.1.15 on 2026-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_websitefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric base price in INR (e.g. 15000.00) — used for sorting and calculations', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing_text',
            field=models.CharField(blank=True, help_text='Pricing highlight for frontend display e.g. Starting at ₹15,000/mo', max_length=150),
        ),
    ]
