# Generated by Django 5.1.15 on 2026-07-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_base_price_alter_service_pricing_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier name e.g. Single Page Website', max_length=200)),
                ('price', models.CharField(help_text='Display price e.g. ₹3,999', max_length=100)),
                ('delivery_time', models.CharField(blank=True, help_text='e.g. Delivered in 3 Days', max_length=150)),
                ('features', models.JSONField(blank=True, default=list, help_text='JSON list of features for this tier e.g. ["1 Page", "Mobile Responsive", "WhatsApp Button"]')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight as the most popular / recommended tier')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the service')),
                ('service', models.ForeignKey(help_text='Parent service this pricing tier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='api.service')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['order', 'id'],
            },
        ),
    ]
