# Generated by Django 5.1.15 on 2026-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pricingtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='district',
            field=models.CharField(blank=True, help_text='District/City e.g. Mumbai, Patna, Roorkee', max_length=100),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='state',
            field=models.CharField(blank=True, help_text='State e.g. Maharashtra, Bihar, Delhi', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='role_applied',
            field=models.CharField(choices=[('Frontend Developer (React/Next.js)', 'Frontend Developer (React/Next.js)'), ('Backend Developer (Python/Node.js)', 'Backend Developer (Python/Node.js)'), ('Full-Stack Developer', 'Full-Stack Developer'), ('UI/UX & Web Designer', 'UI/UX & Web Designer'), ('WordPress / Shopify Expert', 'WordPress / Shopify Expert'), ('App Developer (Flutter/React Native)', 'App Developer (Flutter/React Native)'), ('Graphic Designer (Canva/Photoshop)', 'Graphic Designer (Canva/Photoshop)'), ('Video Editor (Reels/YouTube)', 'Video Editor (Reels/YouTube)'), ('Social Media Manager', 'Social Media Manager'), ('Performance Marketer (Meta/Google Ads)', 'Performance Marketer (Meta/Google Ads)'), ('SEO Specialist (Local & Global)', 'SEO Specialist (Local & Global)'), ('Content Writer / Copywriter', 'Content Writer / Copywriter'), ('Telecaller / Lead Generator', 'Telecaller / Lead Generator'), ('IoT & Hardware Prototype Engineer', 'IoT & Hardware Prototype Engineer'), ('Data Entry / Virtual Assistant', 'Data Entry / Virtual Assistant')], default='Full-Stack Developer', max_length=200),
        ),
    ]
