# Generated by Django 5.1.15 on 2026-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_careerapplication_district_careerapplication_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Agency or Company Name', max_length=250)),
                ('contact_person', models.CharField(help_text='Primary Contact Person', max_length=200)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp Number for Project Handover', max_length=30)),
                ('email', models.EmailField(help_text='Official Business Email', max_length=254)),
                ('core_services', models.CharField(choices=[('Video Editing', 'Video Editing'), ('App Development', 'App Development'), ('SEO', 'SEO'), ('Graphic Design', 'Graphic Design'), ('Performance Ads', 'Performance Ads'), ('Custom Software', 'Custom Software'), ('Other', 'Other')], default='Video Editing', max_length=100)),
                ('portfolio_link', models.URLField(help_text='Agency Website, Case Studies, or Drive Link', max_length=500)),
                ('team_size', models.CharField(choices=[('1-5', '1-5 Members'), ('5-15', '5-15 Members'), ('15+', '15+ Members')], default='1-5', max_length=30)),
                ('proposal', models.TextField(blank=True, help_text='Brief pitch or overflow capacity details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agency Partner Lead',
                'verbose_name_plural': 'Agency Partner Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
