# Generated by Django 5.1.15 on 2026-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_agencypartnerlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='Tick when this applicant has been hired and added as a CRM Team Member.'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='Tick when this lead has been converted to a CRM Client record.'),
        ),
    ]
