# Generated by Django 5.1.15 on 2026-07-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_is_converted_to_leads_and_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of requestor', max_length=200)),
                ('phone', models.CharField(help_text='Phone or WhatsApp number', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Check when callback has been completed')),
            ],
            options={
                'verbose_name': 'Callback Request',
                'verbose_name_plural': 'Callback Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
