# Generated by Django 5.1.15 on 2026-07-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_callbackrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='district',
            field=models.CharField(blank=True, help_text='District/City e.g. Mumbai, Patna, Roorkee', max_length=100),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='state',
            field=models.CharField(blank=True, help_text='State e.g. Maharashtra, Bihar, Delhi', max_length=100),
        ),
    ]
