# Generated by Django 5.1.15 on 2026-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_name_callbackrequest_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypartnerlead',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100),
        ),
        migrations.AddField(
            model_name='agencypartnerlead',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100),
        ),
        migrations.AddField(
            model_name='agencypartnerlead',
            name='town',
            field=models.CharField(blank=True, help_text='Town or City', max_length=100),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='town',
            field=models.CharField(blank=True, help_text='Town or City', max_length=100),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='town',
            field=models.CharField(blank=True, help_text='Town or City', max_length=100),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100),
        ),
    ]
