# Generated by Django 5.1.15 on 2026-07-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_agencypartnerlead_district_agencypartnerlead_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='hire_status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Interviewing', 'Interviewing'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', help_text='Application hiring pipeline status', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Assigned Employee ID e.g. URB-DEV-001', max_length=50, unique=True)),
                ('role', models.CharField(default='Team Member', help_text='e.g. Senior Video Editor, Tech Lead', max_length=150)),
                ('department', models.CharField(default='Production', help_text='e.g. Media Production, Engineering', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80', max_length=500, null=True)),
                ('can_view_finance', models.BooleanField(default=False, help_text='If True, user can view P&L metrics, financial cards, and payouts ledger.')),
                ('can_view_all_projects', models.BooleanField(default=False, help_text='If True, user sees all agency projects. If False, only assigned projects.')),
                ('is_agency_admin', models.BooleanField(default=False, help_text='If True, user has full agency administrative access.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
