# Generated by Django 5.1.15 on 2026-07-28 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_careerapplication_hire_status_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_active_projects_card', models.BooleanField(default=True, help_text='Controls visibility of Active Projects overview card.')),
                ('can_view_pending_tasks_card', models.BooleanField(default=True, help_text='Controls visibility of Pending Tasks overview card.')),
                ('can_view_financials_and_payouts', models.BooleanField(default=False, help_text='Controls visibility of Unbilled / Pending Payouts card (₹) & Payouts Ledger.')),
                ('can_view_project_timeline', models.BooleanField(default=True, help_text='Controls visibility of Active Project Timeline section.')),
                ('can_view_priority_queue', models.BooleanField(default=True, help_text='Controls visibility of Priority Task Queue card.')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permissions', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permissions', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Dashboard Card Permission',
                'verbose_name_plural': 'Dashboard Card Permissions',
            },
        ),
    ]
