# Generated by Django 5.1.15 on 2026-07-28 13:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dashboardpermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Core Team Member',
                'verbose_name_plural': 'Core Team',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
