# Generated by Django 5.1.15 on 2026-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_coreteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_update_email',
            field=models.BooleanField(default=False, help_text='Check this to generate a new password and email the user with their updated role and new credentials.'),
        ),
    ]
