# Generated by Django 5.1.15 on 2026-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile_send_update_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='send_hired_email',
            field=models.BooleanField(default=False, help_text='Check this box and save to generate credentials and send the official Hired email to the applicant.'),
        ),
    ]
