# Generated by Django 5.1.15 on 2026-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_careerapplication_send_hired_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='assigned_services',
            field=models.ManyToManyField(blank=True, help_text='Select services this applicant will have access to (mainly for Freelancers).', to='api.service'),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='team_category',
            field=models.CharField(blank=True, choices=[('Core Team', 'Core Team'), ('Freelancer Team', 'Freelancer Team')], help_text='Select which team this hired applicant will join.', max_length=50, null=True),
        ),
    ]
