# Generated by Django 5.1.15 on 2026-07-30 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_team_category_services_to_career_and_freelancer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, help_text='Invoice number e.g. URB-INV-2026-088.', max_length=100)),
                ('month', models.CharField(help_text='Display month e.g. July 2026.', max_length=80)),
                ('project_title', models.CharField(blank=True, help_text='Project(s) this payout covers.', max_length=300)),
                ('base_amount', models.PositiveIntegerField(default=0, help_text='Base payout amount in INR.')),
                ('bonus_amount', models.PositiveIntegerField(default=0, help_text='Bonus / performance incentive in INR.')),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='Total payout in INR. Auto-calculated as base + bonus if left at 0.')),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('On Hold', 'On Hold')], default='Pending Approval', max_length=30)),
                ('due_date', models.CharField(blank=True, help_text='Display due date e.g. 05 Aug 2026.', max_length=50)),
                ('paid_date', models.CharField(blank=True, help_text='Display paid date e.g. 04 Jul 2026 (fill when status=Paid).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Team member this payout belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Payout',
                'verbose_name_plural': 'Assigned Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title shown in the portal.', max_length=300)),
                ('client_name', models.CharField(help_text='Client or company name.', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Work category e.g. VFX & Motion Graphics.', max_length=150)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('On Hold', 'On Hold')], default='In Progress', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage 0–100.')),
                ('deadline', models.CharField(blank=True, help_text='Display deadline e.g. 04 Aug 2026.', max_length=50)),
                ('deliverable_type', models.CharField(blank=True, help_text='e.g. 4K Cinematic Reel & UI Animations.', max_length=250)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('payout_est', models.PositiveIntegerField(default=0, help_text='Estimated payout for this project in INR (shown only if finance permissions are granted).')),
                ('team_members', models.JSONField(blank=True, default=list, help_text='JSON list of team member display names sharing this project e.g. ["Gaurav S.", "Rohan K."].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Team member responsible for this project.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Project',
                'verbose_name_plural': 'Assigned Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task description shown in the task board.', max_length=400)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=20)),
                ('due_date', models.CharField(blank=True, help_text='Display due date e.g. 02 Aug 2026.', max_length=50)),
                ('estimated_hours', models.PositiveSmallIntegerField(default=1, help_text='Estimated hours to complete this task.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Team member this task is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Parent project this task belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.assignedproject')),
            ],
            options={
                'verbose_name': 'Assigned Task',
                'verbose_name_plural': 'Assigned Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
