# Generated by Django 5.1.15 on 2026-07-30 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_assigned_project_task_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full Name of the Call Partner applicant', max_length=200)),
                ('email', models.EmailField(help_text='Official / Personal Email Address', max_length=254)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp Phone Number for communication', max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Application approval status. Changing to 'Accepted' automatically creates a User account and dispatches welcome email.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Call Partner Application',
                'verbose_name_plural': 'Call Partner Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_call_partner',
            field=models.BooleanField(default=False, help_text='If True, user is an approved Call Partner who can submit client leads for commission.'),
        ),
        migrations.CreateModel(
            name='ClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client Name or Business Name', max_length=200)),
                ('client_phone', models.CharField(help_text='Client Phone or WhatsApp number', max_length=30)),
                ('project_type', models.CharField(help_text='Type of project e.g. Business Website, E-Commerce, Video Editing, Ads', max_length=150)),
                ('discussed_price', models.CharField(blank=True, help_text='Deal / Discussed Amount e.g. ₹15,000', max_length=100)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Payment Processed - 48 Hours', 'Payment Processed - 48 Hours'), ('Rejected', 'Rejected')], default='Under Review', help_text='Pipeline status for this referred client lead.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(help_text='Call Partner user who referred/submitted this lead.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_client_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Lead',
                'verbose_name_plural': 'Client Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
