# Generated by Django 5.1.15 on 2026-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_call_partner_program_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypartnerlead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Application approval status. Changing to 'Accepted' automatically creates a User account and dispatches welcome email.", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_agency_partner',
            field=models.BooleanField(default=False, help_text='If True, user is an approved B2B Agency Partner.'),
        ),
    ]
