# Generated by Django 5.1.15 on 2026-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_agencypartnerlead_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpayout',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending Approval', max_length=30),
        ),
    ]
