# Generated by Django 5.1.15 on 2026-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_assignedpayout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='role_applied',
            field=models.CharField(default='Full-Stack Developer', help_text='Primary skill or role applied for.', max_length=200),
        ),
    ]
