# Generated by Django 5.1.15 on 2026-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies, e.g. "React, Django, PostgreSQL"', max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('live_link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('EdTech', 'EdTech'), ('Web App', 'Web App'), ('Hardware Logic', 'Hardware Logic'), ('SaaS', 'SaaS'), ('E-Commerce', 'E-Commerce'), ('Mobile App', 'Mobile App'), ('Dashboard', 'Dashboard'), ('Other', 'Other')], default='Web App', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
