# Generated by Django 5.1.15 on 2026-07-19 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable category label.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier — auto-filled from name if left blank.', max_length=110, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional one-liner shown as a filter tooltip.', max_length=300)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title shown on the Services page.', max_length=200)),
                ('short_description', models.TextField(help_text='One-to-two sentence summary shown in service cards.')),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier, e.g. "Globe", "Paintbrush2" (Lucide) or "fa-solid fa-code" (Font Awesome).', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Drag-and-drop ordering via admin.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this service without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client or company name — leave blank for internal projects.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub / source repository URL (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a project screenshot (preferred over image_url).', null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Public URL of the deployed project.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Full project description (supports Markdown).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL — used if no file is uploaded.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin to the home-page hero / featured section.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated technologies, e.g. "React, Django, PostgreSQL".', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title shown on cards and the detail page.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(help_text='The taxonomy category this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category'),
        ),
    ]
