# Generated by Django 5.1.15 on 2026-07-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_service_remove_project_live_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Full case-study body shown on the detail page. Supports Markdown. Include challenges, solutions, and outcomes.'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier — auto-filled from title if left blank.', max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier — auto-filled from title if left blank.', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short project description shown on portfolio cards (supports Markdown).'),
        ),
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(help_text='Display name for this tier/option (e.g. "Small Business Website").', max_length=200)),
                ('price_string', models.CharField(help_text='Human-readable price label (e.g. "Starts at $499", "From £799/mo").', max_length=100)),
                ('features', models.JSONField(default=list, help_text='JSON array of feature bullet points shown on the pricing card. Example: ["Responsive design", "SEO optimised", "3 revisions"]')),
                ('delivery_time', models.CharField(blank=True, help_text='Estimated delivery time (e.g. "5–7 business days", "2–4 weeks").', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this tier as the recommended / most popular option.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first in the pricing grid.')),
                ('service', models.ForeignKey(help_text='The parent service this tier belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='portfolio.service')),
            ],
            options={
                'verbose_name': 'Service Tier',
                'verbose_name_plural': 'Service Tiers',
                'ordering': ['order', 'tier_name'],
            },
        ),
    ]
