# Generated by Django 5.1.15 on 2026-07-25 07:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('role_applied_for', models.CharField(max_length=200)),
                ('portfolio_link', models.URLField(blank=True, help_text="Optional link to the applicant's portfolio or GitHub profile.", null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(help_text='Primary point-of-contact name.', max_length=200)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative revenue billed to this client (auto-updated or managed manually).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('service_interested', models.CharField(help_text='The service the prospect is enquiring about.', max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g. "Frontend Developer", "Designer"', max_length=100)),
                ('is_freelancer', models.BooleanField(default=False, help_text='Tick if this person is a freelancer rather than a full-time employee.')),
                ('standard_charge', models.DecimalField(decimal_places=2, help_text='Standard per-task or per-hour charge paid to this member (in your base currency).', max_digits=10)),
                ('average_rating', models.FloatField(default=0.0, help_text='Computed average performance rating across all tasks (0.0 – 5.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_tasks_completed', models.IntegerField(default=0, help_text='Running count of tasks marked Completed and assigned to this member.', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('client_charged_amount', models.DecimalField(decimal_places=2, help_text='Amount billed to the client for this task.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('freelancer_paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid to the assigned freelancer/employee for this task.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('performance_rating', models.IntegerField(help_text='Performance rating for this task (1 = Poor, 5 = Excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.client')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team member responsible for this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.teammember')),
            ],
            options={
                'verbose_name': 'Project Task',
                'verbose_name_plural': 'Project Tasks',
                'ordering': ['-id'],
            },
        ),
    ]
