# Generated by Django 5.1.15 on 2026-07-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelance Team'},
        ),
    ]
