# Generated by Django 5.1.15 on 2026-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_teammember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='send_update_email',
            field=models.BooleanField(default=False, help_text='Check this to generate a new password and email the user with their updated role and new credentials.'),
        ),
    ]
