# Generated by Django 5.1.15 on 2026-07-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_teammember_send_update_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for notifications and credential updates.', max_length=254, null=True),
        ),
    ]
