# Generated by Django 5.1.15 on 2026-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_team_category_services_to_career_and_freelancer'),
        ('crm', '0004_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services this freelancer is authorized to handle.', to='api.service'),
        ),
    ]
