# Generated by Django 5.1.15 on 2026-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_team_category_services_to_career_and_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='district',
            field=models.CharField(blank=True, help_text='District as submitted in the career application.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone / WhatsApp number from the original career application.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='portfolio_link',
            field=models.URLField(blank=True, help_text='Portfolio, resume, or work-sample URL from the career application.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='state',
            field=models.CharField(blank=True, help_text='State as submitted in the career application.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='town',
            field=models.CharField(blank=True, help_text='Town / City as submitted in the career application.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='why_join_us',
            field=models.TextField(blank=True, help_text="Applicant's motivation / cover letter from the career application.", null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='e.g. "Frontend Developer", "Designer"', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='standard_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard per-task or per-hour charge paid to this member (in your base currency).', max_digits=10),
        ),
    ]
