# Generated by Django 5.1.15 on 2026-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_application_details_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Uploaded Payment QR Code image', null=True, upload_to='payment_qrs/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='upi_id',
            field=models.CharField(blank=True, help_text="Freelancer's UPI ID e.g. user@okicici", max_length=100, null=True),
        ),
    ]
