# Generated by Django 5.1.15 on 2026-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g. +91 98765 43210', max_length=20)),
                ('service_required', models.CharField(choices=[('website', 'Website Development'), ('webapp', 'Web Application'), ('mobile', 'Mobile App'), ('saas', 'SaaS Development'), ('maintenance', 'Monthly Maintenance'), ('consulting', 'Tech Consulting'), ('other', 'Other')], default='other', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
